import os
import gspread
import requests
import datetime
import smtplib
import pandas as pd
from dotenv import load_dotenv
from email.mime.multipart import MIMEMultipart
from email.mime.text import MIMEText
from email.mime.application import MIMEApplication

load_dotenv()

PIPELINE_COLUMNS = ["record_id", "source", "title", "status", "priority"]

def fetch_github_data():
    api_url = "https://api.github.com/repos/psf/requests/issues"
    print("Fetching open issues from GitHub...")
    response = requests.get(api_url, timeout=10)
    response.raise_for_status()
    issues_data = response.json()[:3]

    records = []
    for issue in issues_data:
        records.append({
            "record_id": issue["number"],
            "source": "GitHub",
            "title": issue["title"],
            "status": issue["state"],
            "priority": "Medium",
        })

    return pd.DataFrame.from_records(records, columns=PIPELINE_COLUMNS)

def fetch_salesforce_data():
    print("Fetching mock CRM data...")
    mock_salesforce_response = [
        {"Id": "006Dp000002Xb", "Name": "Acme Corp Q4 Deal", "StageName": "Negotiation", "Probability": 80},
        {"Id": "006Dp000002Xc", "Name": "Server Upgrade Expansion", "StageName": "Prospecting", "Probability": 20},
        {"Id": "006Dp000002Xd", "Name": "Global License Renewal", "StageName": "Closed Won", "Probability": 100}
    ]

    records = []
    for opp in mock_salesforce_response:
        calculated_priority = "High" if opp['Probability'] >= 80 else "Low"
        records.append({
            "record_id": opp["Id"],
            "source": "Mock CRM",
            "title": opp["Name"],
            "status": opp["StageName"],
            "priority": calculated_priority,
        })

    return pd.DataFrame.from_records(records, columns=PIPELINE_COLUMNS)

def normalize_pipeline_data(dataframes):
    combined = pd.concat(dataframes, ignore_index=True)
    combined = combined.dropna(subset=["record_id", "source", "title"])
    combined["record_id"] = combined["record_id"].astype(str).str.strip()
    combined["source"] = combined["source"].astype(str).str.strip()
    combined["title"] = combined["title"].astype(str).str.strip()
    combined["status"] = combined["status"].astype(str).str.strip().str.title()
    combined["priority"] = combined["priority"].fillna("Unassigned").astype(str).str.strip().str.title()
    combined = combined.drop_duplicates(subset=["source", "record_id"])
    combined = combined.sort_values(["source", "priority", "title"])
    return combined[PIPELINE_COLUMNS]

def send_email(pdf_filename):
    print("Connecting to email server...")
    sender_email = os.getenv("SENDER_EMAIL")
    sender_password = os.getenv("SENDER_APP_PASSWORD")
    receiver_email = os.getenv("RECEIVER_EMAIL")

    msg = MIMEMultipart()
    msg['From'] = sender_email
    msg['To'] = receiver_email
    msg['Subject'] = "Automated Weekly Status Report"

    body = "Hello,\n\nPlease find the automated weekly status report attached.\n\nGenerated by Python."
    msg.attach(MIMEText(body, 'plain'))

    with open(pdf_filename, "rb") as attachment:
        part = MIMEApplication(attachment.read(), Name=pdf_filename)
        part['Content-Disposition'] = f'attachment; filename="{pdf_filename}"'
        msg.attach(part)

        server = smtplib.SMTP('smtp.gmail.com', 587)
        server.starttls()
        server.login(sender_email, sender_password)
        server.sendmail(sender_email, receiver_email, msg.as_string())
        server.quit()
        print("Success! Email delivered.")

def main():
    print("Starting ETL Pipeline:")
    github_df = fetch_github_data()
    salesforce_df = fetch_salesforce_data()
    final_df = normalize_pipeline_data([github_df, salesforce_df])
    all_rows = final_df.values.tolist()

    print(f"Total normalized rows ready to load: {len(all_rows)}")

    print("Authenticated with Google Sheets...")
    gc = gspread.service_account(filename='credentials.json')
    spreadsheet = gc.open('Automated_Status_DB')
    
    raw_sheet = spreadsheet.worksheet('Raw_Data')
    raw_sheet.append_rows(all_rows)
    print("Data successfully loaded into Raw_Data sheet.")

    summary_sheet = spreadsheet.worksheet('Weekly_Summary')
    today = datetime.date.today().strftime("%Y-%m-%d")
    status_msg = f"Pipeline ingested {len(all_rows)} cross-system items."
    summary_sheet.append_row([today, len(all_rows), status_msg])

    print("Generating PDF Snapshot...")
    sheet_id = spreadsheet.id
    tab_id = summary_sheet.id

    export_url = f"https://docs.google.com/spreadsheets/d/{sheet_id}/export?format=pdf&gid={tab_id}"

    response = gc.http_client.request('get', export_url)
    pdf_filename = f"Weekly_Status_{today}.pdf"

    with open(pdf_filename, 'wb') as file:
        file.write(response.content)
    
    print(f"Success! PDF saved locallly as {pdf_filename}")
    send_email(pdf_filename)

    print("Pipeline Complete.")
    
if __name__ == "__main__":
    main()
